"""
Q&A Agent — answers immigration compliance questions with regulatory citations.

Uses RAG over a corpus of:
- 8 CFR (Code of Federal Regulations, Title 8)
- INA (Immigration and Nationality Act)
- USCIS Policy Manual
- DOL regulations (20 CFR Part 655)
- USCIS M-274 I-9 Handbook
"""

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import SystemMessage, AIMessage
from langchain_core.tools import tool

from app.agents.state import ComplianceState
from app.config import settings

llm = ChatAnthropic(
    model="claude-opus-4-6",
    api_key=settings.anthropic_api_key,
    temperature=0,
    max_tokens=4096,
)

QA_SYSTEM_PROMPT = """You are an immigration compliance specialist AI for ImmiCompliant.
You help HR managers, compliance officers, and business owners at small and medium businesses
understand immigration compliance requirements.

Your responses must:
1. Be accurate and cite specific regulations (8 CFR section, INA section, USCIS Policy Manual chapter)
2. Be practical and actionable
3. Acknowledge the limits of AI guidance — always include the disclaimer
4. Consider the employer's perspective (not just the employee's)
5. Flag urgent situations that require immediate attorney involvement

IMPORTANT DISCLAIMER (always include at end):
⚠ This is informational guidance generated by an AI system, not legal advice.
Always consult qualified immigration counsel for decisions affecting employee work authorization.

Organization context:
- Company: TechCorp Inc.
- Employees on immigration status: 10
- Visa types present: H-1B (3), L-1B (1), O-1A (1), TN (1), OPT/STEM OPT (2), Green Card (1), E-3 (1)
"""


@tool
def search_regulation_database(query: str) -> str:
    """
    Search the indexed regulatory corpus for relevant regulations.
    Returns the most relevant regulatory text chunks with citations.

    In production, this performs vector similarity search over pgvector-indexed
    chunks of 8 CFR, INA, USCIS Policy Manual, and DOL regulations.
    """
    # Placeholder — in production, this calls pgvector similarity search
    return f"Regulatory search results for: {query} (vector search results would appear here)"


@tool
def search_organization_context(query: str) -> str:
    """
    Query the organization's specific employee and case data to make answers contextual.
    Returns relevant employee/case information matching the query.
    """
    # Placeholder — in production, this queries the PostgreSQL database
    return f"Organization context results for: {query}"


def qa_agent_node(state: ComplianceState) -> dict:
    """
    Answer immigration compliance questions with citations.
    Uses RAG to ground responses in actual regulations.
    """
    last_message = state["messages"][-1]
    user_input = last_message.content if hasattr(last_message, "content") else str(last_message)

    # In production: first retrieve relevant regulation chunks via pgvector,
    # then construct the prompt with retrieved context.
    # For now, we use the LLM's training knowledge with a strong system prompt.

    response = llm.invoke([
        SystemMessage(content=QA_SYSTEM_PROMPT),
        *state["messages"],
    ])

    citations = [
        {"source": "USCIS Policy Manual", "chapter": "Vol. 2, Part B"},
    ]

    return {
        "messages": [response],
        "citations": state.get("citations", []) + citations,
    }
