import type {
  Employee, Case, Document, I9Record, LCA, PAFRecord,
  PolicyUpdate, Alert, OrgComplianceScore, ComplianceDeadline, ChatMessage
} from './types'

// ─── Employees ──────────────────────────────────────────────────────────────

export const employees: Employee[] = [
  {
    id: 'emp-001',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@company.com',
    department: 'Engineering',
    title: 'Senior Software Engineer',
    location: 'Austin, TX',
    startDate: '2021-03-15',
    visaType: 'H-1B',
    status: 'active',
    workAuthorizationExpiry: '2026-03-14',
    i94Expiry: '2026-03-14',
    passportExpiry: '2027-08-10',
    activeCaseId: 'case-001',
    riskLevel: 'low',
    complianceScore: 94,
    notes: 'H-1B renewal filed in Dec 2025. Premium processing requested.',
    attorney: 'Cohen & Associates',
  },
  {
    id: 'emp-002',
    firstName: 'Wei',
    lastName: 'Zhang',
    email: 'wei.zhang@company.com',
    department: 'Product',
    title: 'Product Manager',
    location: 'San Francisco, CA',
    startDate: '2022-07-01',
    visaType: 'L-1B',
    status: 'expiring_soon',
    workAuthorizationExpiry: '2026-05-12',
    i94Expiry: '2026-05-12',
    passportExpiry: '2028-03-22',
    activeCaseId: 'case-002',
    riskLevel: 'medium',
    complianceScore: 78,
    notes: 'L-1B max 5 years reached. Evaluating L-1A or H-1B options.',
    attorney: 'Fragomen LLP',
  },
  {
    id: 'emp-003',
    firstName: 'Carlos',
    lastName: 'Mendez',
    email: 'carlos.mendez@company.com',
    department: 'Finance',
    title: 'Financial Analyst',
    location: 'Miami, FL',
    startDate: '2023-01-09',
    visaType: 'TN',
    status: 'active',
    workAuthorizationExpiry: '2026-01-08',
    i94Expiry: '2026-01-08',
    passportExpiry: '2029-06-14',
    activeCaseId: null,
    riskLevel: 'low',
    complianceScore: 91,
    notes: 'Canadian citizen. TN renewal at border in Dec 2025.',
    attorney: null,
  },
  {
    id: 'emp-004',
    firstName: 'Aisha',
    lastName: 'Okonkwo',
    email: 'aisha.okonkwo@company.com',
    department: 'Engineering',
    title: 'ML Engineer',
    location: 'New York, NY',
    startDate: '2023-08-21',
    visaType: 'OPT',
    status: 'action_required',
    workAuthorizationExpiry: '2024-08-20',
    i94Expiry: '2027-05-15',
    passportExpiry: '2028-11-30',
    activeCaseId: 'case-003',
    riskLevel: 'high',
    complianceScore: 55,
    notes: 'OPT expired! STEM OPT extension filed but EAD not yet received. On cap-gap period.',
    attorney: 'Berry Appleman & Leiden',
  },
  {
    id: 'emp-005',
    firstName: 'Kenji',
    lastName: 'Tanaka',
    email: 'kenji.tanaka@company.com',
    department: 'Design',
    title: 'UX Director',
    location: 'Seattle, WA',
    startDate: '2020-05-11',
    visaType: 'O-1A',
    status: 'active',
    workAuthorizationExpiry: '2027-05-10',
    i94Expiry: '2027-05-10',
    passportExpiry: '2030-01-05',
    activeCaseId: 'case-004',
    riskLevel: 'low',
    complianceScore: 97,
    notes: 'O-1A renewed for 3 years. All docs current.',
    attorney: 'Klasko Immigration Law Partners',
  },
  {
    id: 'emp-006',
    firstName: 'Fatima',
    lastName: 'Al-Hassan',
    email: 'fatima.alhassan@company.com',
    department: 'Operations',
    title: 'Operations Manager',
    location: 'Chicago, IL',
    startDate: '2019-11-04',
    visaType: 'Green Card',
    status: 'pending',
    workAuthorizationExpiry: '2025-12-01',
    i94Expiry: null,
    passportExpiry: '2026-07-18',
    activeCaseId: 'case-005',
    riskLevel: 'medium',
    complianceScore: 82,
    notes: 'I-485 pending. EAD/AP combo card expires Dec 2025. Renewal filed.',
    attorney: 'Seyfarth Shaw',
  },
  {
    id: 'emp-007',
    firstName: 'Andrei',
    lastName: 'Popescu',
    email: 'andrei.popescu@company.com',
    department: 'Engineering',
    title: 'DevOps Engineer',
    location: 'Austin, TX',
    startDate: '2022-02-14',
    visaType: 'H-1B',
    status: 'active',
    workAuthorizationExpiry: '2025-02-13',
    i94Expiry: '2025-02-13',
    passportExpiry: '2027-09-25',
    activeCaseId: 'case-006',
    riskLevel: 'critical',
    complianceScore: 42,
    notes: 'H-1B EXPIRED. Renewal denied due to specialty occupation issue. Working with attorney on MTR.',
    attorney: 'Ogletree Deakins',
  },
  {
    id: 'emp-008',
    firstName: 'Meera',
    lastName: 'Patel',
    email: 'meera.patel@company.com',
    department: 'HR',
    title: 'HR Business Partner',
    location: 'San Francisco, CA',
    startDate: '2021-09-27',
    visaType: 'H-1B',
    status: 'active',
    workAuthorizationExpiry: '2027-09-26',
    i94Expiry: '2027-09-26',
    passportExpiry: '2029-04-11',
    activeCaseId: null,
    riskLevel: 'low',
    complianceScore: 98,
    notes: 'H-1B approved through 2027. Green Card PERM filed.',
    attorney: 'Fragomen LLP',
  },
  {
    id: 'emp-009',
    firstName: 'Lucas',
    lastName: 'Silva',
    email: 'lucas.silva@company.com',
    department: 'Sales',
    title: 'Sales Engineer',
    location: 'Miami, FL',
    startDate: '2024-01-15',
    visaType: 'E-3',
    status: 'active',
    workAuthorizationExpiry: '2026-01-14',
    i94Expiry: '2026-01-14',
    passportExpiry: '2028-08-30',
    activeCaseId: 'case-007',
    riskLevel: 'low',
    complianceScore: 88,
    notes: 'Australian citizen on E-3. First renewal in progress.',
    attorney: null,
  },
  {
    id: 'emp-010',
    firstName: 'Nadia',
    lastName: 'Kovacs',
    email: 'nadia.kovacs@company.com',
    department: 'Engineering',
    title: 'Data Scientist',
    location: 'New York, NY',
    startDate: '2023-05-08',
    visaType: 'STEM OPT',
    status: 'expiring_soon',
    workAuthorizationExpiry: '2026-05-07',
    i94Expiry: '2026-07-15',
    passportExpiry: '2030-02-20',
    activeCaseId: 'case-008',
    riskLevel: 'medium',
    complianceScore: 75,
    notes: 'STEM OPT expires May 2026. H-1B cap registration needed for Apr 2026 lottery.',
    attorney: 'Berry Appleman & Leiden',
  },
]

// ─── Cases ──────────────────────────────────────────────────────────────────

export const cases: Case[] = [
  {
    id: 'case-001',
    employeeId: 'emp-001',
    caseNumber: 'WAC2512345678',
    caseType: 'Form I-129 (H-1B Extension)',
    visaCategory: 'H-1B',
    status: 'approved',
    filedDate: '2025-12-01',
    approvalDate: '2026-01-15',
    expiryDate: '2029-03-14',
    serviceCenter: 'California Service Center',
    petitionerName: 'TechCorp Inc.',
    beneficiaryName: 'Priya Sharma',
    lastUpdated: '2026-01-15',
    notes: 'Premium processing. Approved in 10 business days.',
    timeline: [
      { id: 'e1', date: '2025-12-01', event: 'Petition Filed', description: 'I-129 filed with premium processing fee', type: 'filing' },
      { id: 'e2', date: '2025-12-03', event: 'Receipt Notice', description: 'Form I-797C received. Receipt# WAC2512345678', type: 'receipt' },
      { id: 'e3', date: '2026-01-15', event: 'Approval Notice', description: 'Form I-797 approval notice received. Valid through 3/14/2029', type: 'approval' },
    ],
  },
  {
    id: 'case-002',
    employeeId: 'emp-002',
    caseNumber: 'SRC2598765432',
    caseType: 'Form I-129 (L-1B to H-1B Change of Status)',
    visaCategory: 'H-1B',
    status: 'pending',
    filedDate: '2026-02-15',
    approvalDate: null,
    expiryDate: null,
    serviceCenter: 'Texas Service Center',
    petitionerName: 'TechCorp Inc.',
    beneficiaryName: 'Wei Zhang',
    lastUpdated: '2026-03-01',
    notes: 'Filed with cap exemption claim (nonprofit research org). Awaiting adjudication.',
    timeline: [
      { id: 'e1', date: '2026-02-15', event: 'Petition Filed', description: 'I-129 H-1B filed. L-1B expires 5/12/2026', type: 'filing' },
      { id: 'e2', date: '2026-02-18', event: 'Receipt Notice', description: 'Form I-797C received. SRC2598765432', type: 'receipt' },
    ],
  },
  {
    id: 'case-003',
    employeeId: 'emp-004',
    caseNumber: 'LIN2601122334',
    caseType: 'Form I-765 (STEM OPT EAD)',
    visaCategory: 'STEM OPT',
    status: 'pending',
    filedDate: '2026-01-20',
    approvalDate: null,
    expiryDate: null,
    serviceCenter: 'Nebraska Service Center',
    petitionerName: 'N/A (Employee Filed)',
    beneficiaryName: 'Aisha Okonkwo',
    lastUpdated: '2026-02-10',
    notes: 'STEM OPT EAD application. School DSO recommended approval. Processing time: ~3 months.',
    timeline: [
      { id: 'e1', date: '2026-01-20', event: 'I-765 Filed', description: 'STEM OPT EAD application filed', type: 'filing' },
      { id: 'e2', date: '2026-01-25', event: 'Receipt Notice', description: 'Receipt notice issued', type: 'receipt' },
    ],
  },
  {
    id: 'case-004',
    employeeId: 'emp-005',
    caseNumber: 'EAC2489012345',
    caseType: 'Form I-129 (O-1A Extension)',
    visaCategory: 'O-1A',
    status: 'approved',
    filedDate: '2024-03-01',
    approvalDate: '2024-04-15',
    expiryDate: '2027-05-10',
    serviceCenter: 'Vermont Service Center',
    petitionerName: 'TechCorp Inc.',
    beneficiaryName: 'Kenji Tanaka',
    lastUpdated: '2024-04-15',
    notes: 'Three-year extension approved.',
    timeline: [
      { id: 'e1', date: '2024-03-01', event: 'Petition Filed', description: 'O-1A extension filed', type: 'filing' },
      { id: 'e2', date: '2024-03-05', event: 'Receipt Notice', description: 'Receipt notice issued', type: 'receipt' },
      { id: 'e3', date: '2024-04-15', event: 'Approved', description: 'O-1A approved for 3 years', type: 'approval' },
    ],
  },
  {
    id: 'case-005',
    employeeId: 'emp-006',
    caseNumber: 'MSC2401234567',
    caseType: 'Form I-485 (Adjustment of Status)',
    visaCategory: 'Green Card',
    status: 'in_progress',
    filedDate: '2023-06-15',
    approvalDate: null,
    expiryDate: null,
    serviceCenter: 'Chicago Field Office',
    petitionerName: 'TechCorp Inc.',
    beneficiaryName: 'Fatima Al-Hassan',
    lastUpdated: '2026-01-10',
    notes: 'Priority date: Feb 2019 (EB-2, ROW). Currently backlogged. Biometrics completed.',
    timeline: [
      { id: 'e1', date: '2023-06-15', event: 'I-485 Filed', description: 'Adjustment of Status package filed', type: 'filing' },
      { id: 'e2', date: '2023-07-01', event: 'Biometrics Appointment', description: 'Biometrics completed at Chicago ASC', type: 'update' },
      { id: 'e3', date: '2024-02-20', event: 'Interview Scheduled', description: 'Interview notice received for Mar 15, 2024', type: 'update' },
      { id: 'e4', date: '2024-03-15', event: 'Interview Completed', description: 'Interview completed. Case continued for additional review.', type: 'update' },
    ],
  },
  {
    id: 'case-006',
    employeeId: 'emp-007',
    caseNumber: 'EAC2401987654',
    caseType: 'Form I-290B (MTR - H-1B Denial)',
    visaCategory: 'H-1B',
    status: 'rfe_received',
    filedDate: '2025-03-10',
    approvalDate: null,
    expiryDate: null,
    serviceCenter: 'Vermont Service Center',
    petitionerName: 'TechCorp Inc.',
    beneficiaryName: 'Andrei Popescu',
    lastUpdated: '2026-02-20',
    notes: 'MTR filed. AAO issued NOID. Response due 3/25/2026. CRITICAL.',
    timeline: [
      { id: 'e1', date: '2025-02-01', event: 'H-1B Denied', description: 'H-1B renewal denied — specialty occupation not established', type: 'denial' },
      { id: 'e2', date: '2025-03-10', event: 'MTR Filed', description: 'Motion to Reconsider filed with AAO', type: 'filing' },
      { id: 'e3', date: '2026-02-20', event: 'NOID Issued', description: 'Notice of Intent to Deny received from AAO', type: 'rfe' },
    ],
  },
  {
    id: 'case-007',
    employeeId: 'emp-009',
    caseNumber: 'E3-2024-MIA-001',
    caseType: 'E-3 Visa (Consular)',
    visaCategory: 'E-3',
    status: 'approved',
    filedDate: '2024-01-02',
    approvalDate: '2024-01-10',
    expiryDate: '2026-01-14',
    serviceCenter: 'U.S. Consulate Sydney',
    petitionerName: 'TechCorp Inc.',
    beneficiaryName: 'Lucas Silva',
    lastUpdated: '2024-01-10',
    notes: 'E-3 stamped at Sydney consulate. Renewal pending.',
    timeline: [
      { id: 'e1', date: '2024-01-02', event: 'DS-160 Filed', description: 'Visa application submitted', type: 'filing' },
      { id: 'e2', date: '2024-01-10', event: 'Visa Stamped', description: 'E-3 visa stamp in passport. Valid 2 years.', type: 'approval' },
    ],
  },
  {
    id: 'case-008',
    employeeId: 'emp-010',
    caseNumber: 'H1B-CAP-2026-010',
    caseType: 'H-1B Cap Registration',
    visaCategory: 'H-1B',
    status: 'in_progress',
    filedDate: '2026-03-01',
    approvalDate: null,
    expiryDate: null,
    serviceCenter: 'USCIS Electronic Registration',
    petitionerName: 'TechCorp Inc.',
    beneficiaryName: 'Nadia Kovacs',
    lastUpdated: '2026-03-01',
    notes: 'Cap registration submitted. Lottery results expected April 2026.',
    timeline: [
      { id: 'e1', date: '2026-03-01', event: 'Cap Registration', description: 'H-1B cap registration submitted for FY2027 lottery', type: 'filing' },
    ],
  },
]

// ─── Documents ───────────────────────────────────────────────────────────────

export const documents: Document[] = [
  { id: 'doc-001', employeeId: 'emp-001', caseId: 'case-001', name: 'I-9 Form - Priya Sharma', type: 'i9', uploadedAt: '2021-03-15', uploadedBy: 'HR Admin', expiryDate: null, fileSize: '245 KB', status: 'valid', tags: ['i9', 'onboarding'] },
  { id: 'doc-002', employeeId: 'emp-001', caseId: 'case-001', name: 'I-797 Approval Notice - H-1B 2026', type: 'approval_notice', uploadedAt: '2026-01-16', uploadedBy: 'HR Admin', expiryDate: '2029-03-14', fileSize: '180 KB', status: 'valid', tags: ['h1b', 'approval'] },
  { id: 'doc-003', employeeId: 'emp-001', caseId: null, name: 'LCA ETA-9035E - Priya Sharma', type: 'lca', uploadedAt: '2025-11-20', uploadedBy: 'Attorney', expiryDate: '2029-03-14', fileSize: '320 KB', status: 'valid', tags: ['lca', 'paf'] },
  { id: 'doc-004', employeeId: 'emp-002', caseId: null, name: 'I-9 Form - Wei Zhang', type: 'i9', uploadedAt: '2022-07-01', uploadedBy: 'HR Admin', expiryDate: null, fileSize: '198 KB', status: 'valid', tags: ['i9'] },
  { id: 'doc-005', employeeId: 'emp-004', caseId: 'case-003', name: 'I-9 Form - Aisha Okonkwo (Reverification Due)', type: 'i9', uploadedAt: '2023-08-21', uploadedBy: 'HR Admin', expiryDate: '2024-08-20', fileSize: '212 KB', status: 'expired', tags: ['i9', 'reverification-needed'] },
  { id: 'doc-006', employeeId: 'emp-007', caseId: 'case-006', name: 'H-1B Denial Notice - Andrei Popescu', type: 'approval_notice', uploadedAt: '2025-02-05', uploadedBy: 'Attorney', expiryDate: null, fileSize: '156 KB', status: 'under_review', tags: ['denial', 'h1b', 'urgent'] },
  { id: 'doc-007', employeeId: 'emp-008', caseId: null, name: 'LCA ETA-9035E - Meera Patel', type: 'lca', uploadedAt: '2024-09-01', uploadedBy: 'Attorney', expiryDate: '2027-09-26', fileSize: '298 KB', status: 'valid', tags: ['lca', 'paf'] },
  { id: 'doc-008', employeeId: 'emp-005', caseId: 'case-004', name: 'I-797 Approval Notice - O-1A 2024', type: 'approval_notice', uploadedAt: '2024-04-16', uploadedBy: 'HR Admin', expiryDate: '2027-05-10', fileSize: '175 KB', status: 'valid', tags: ['o1a', 'approval'] },
  { id: 'doc-009', employeeId: 'emp-003', caseId: null, name: 'TN Approval (I-94) - Carlos Mendez', type: 'approval_notice', uploadedAt: '2025-01-09', uploadedBy: 'HR Admin', expiryDate: '2026-01-08', fileSize: '134 KB', status: 'expiring', tags: ['tn', 'i94'] },
  { id: 'doc-010', employeeId: null, caseId: null, name: 'Public Access File - Priya Sharma LCA 2026', type: 'paf', uploadedAt: '2025-11-21', uploadedBy: 'HR Admin', expiryDate: '2029-03-14', fileSize: '1.2 MB', status: 'valid', tags: ['paf', 'h1b'] },
]

// ─── I-9 Records ─────────────────────────────────────────────────────────────

export const i9Records: I9Record[] = [
  {
    id: 'i9-001', employeeId: 'emp-001',
    section1CompletedDate: '2021-03-15', section2CompletedDate: '2021-03-17',
    section3CompletedDate: null,
    listADocument: 'Passport (India) + I-94', listBDocument: null, listCDocument: null,
    workAuthorizationExpiry: '2026-03-14', reverificationDue: '2026-03-14',
    errors: [], status: 'complete', lastReviewed: '2026-01-15',
  },
  {
    id: 'i9-002', employeeId: 'emp-002',
    section1CompletedDate: '2022-07-01', section2CompletedDate: '2022-07-03',
    section3CompletedDate: null,
    listADocument: 'Passport (China) + I-94', listBDocument: null, listCDocument: null,
    workAuthorizationExpiry: '2026-05-12', reverificationDue: '2026-05-12',
    errors: [], status: 'complete', lastReviewed: '2025-12-01',
  },
  {
    id: 'i9-003', employeeId: 'emp-003',
    section1CompletedDate: '2023-01-09', section2CompletedDate: '2023-01-10',
    section3CompletedDate: null,
    listADocument: null, listBDocument: "Driver's License (FL)", listCDocument: "I-94 (TN)",
    workAuthorizationExpiry: '2026-01-08', reverificationDue: '2026-01-08',
    errors: [], status: 'complete', lastReviewed: '2025-11-15',
  },
  {
    id: 'i9-004', employeeId: 'emp-004',
    section1CompletedDate: '2023-08-21', section2CompletedDate: '2023-08-23',
    section3CompletedDate: null,
    listADocument: 'EAD (OPT)', listBDocument: null, listCDocument: null,
    workAuthorizationExpiry: '2024-08-20', reverificationDue: '2024-08-20',
    errors: [
      { field: 'Section 3', severity: 'major', description: 'Reverification overdue — OPT EAD expired 8/20/2024. New EAD not yet received.', correctionRequired: true },
    ],
    status: 'needs_reverification', lastReviewed: '2024-08-01',
  },
  {
    id: 'i9-005', employeeId: 'emp-005',
    section1CompletedDate: '2020-05-11', section2CompletedDate: '2020-05-13',
    section3CompletedDate: '2024-04-16',
    listADocument: 'Passport (Japan) + I-94', listBDocument: null, listCDocument: null,
    workAuthorizationExpiry: '2027-05-10', reverificationDue: '2027-05-10',
    errors: [], status: 'reverified', lastReviewed: '2024-04-16',
  },
  {
    id: 'i9-006', employeeId: 'emp-007',
    section1CompletedDate: '2022-02-14', section2CompletedDate: '2022-02-16',
    section3CompletedDate: null,
    listADocument: 'Passport (Romania) + I-94', listBDocument: null, listCDocument: null,
    workAuthorizationExpiry: '2025-02-13', reverificationDue: '2025-02-13',
    errors: [
      { field: 'Section 3', severity: 'major', description: 'Reverification OVERDUE — H-1B expired 2/13/2025. No valid work authorization. Consult counsel immediately.', correctionRequired: true },
      { field: 'Section 2', severity: 'minor', description: 'Document title abbreviation unclear.', correctionRequired: false },
    ],
    status: 'errors', lastReviewed: '2025-01-10',
  },
  {
    id: 'i9-007', employeeId: 'emp-008',
    section1CompletedDate: '2021-09-27', section2CompletedDate: '2021-09-28',
    section3CompletedDate: '2024-10-01',
    listADocument: 'Passport (India) + I-94', listBDocument: null, listCDocument: null,
    workAuthorizationExpiry: '2027-09-26', reverificationDue: '2027-09-26',
    errors: [], status: 'reverified', lastReviewed: '2024-10-01',
  },
]

// ─── LCAs ────────────────────────────────────────────────────────────────────

export const lcas: LCA[] = [
  {
    id: 'lca-001', caseNumber: 'I-200-25001-123456', employeeId: 'emp-001',
    socCode: '15-1252', jobTitle: 'Software Developer',
    wageLevel: 'III', offeredWage: 145000, prevailingWage: 128000,
    workLocation: 'Austin, TX 78701',
    filedDate: '2025-11-10', certifiedDate: '2025-11-20',
    validityStart: '2026-03-15', validityEnd: '2029-03-14',
    postingStartDate: '2025-11-20', postingEndDate: '2025-12-01',
    postingCompleted: true, pafComplete: true, status: 'certified',
  },
  {
    id: 'lca-002', caseNumber: 'I-200-26001-234567', employeeId: 'emp-002',
    socCode: '11-2021', jobTitle: 'Marketing Manager',
    wageLevel: 'II', offeredWage: 120000, prevailingWage: 115000,
    workLocation: 'San Francisco, CA 94105',
    filedDate: '2026-01-15', certifiedDate: '2026-01-25',
    validityStart: '2026-05-12', validityEnd: '2029-05-11',
    postingStartDate: '2026-01-25', postingEndDate: '2026-02-06',
    postingCompleted: true, pafComplete: false, status: 'certified',
  },
  {
    id: 'lca-003', caseNumber: 'I-200-24001-345678', employeeId: 'emp-008',
    socCode: '13-1071', jobTitle: 'Human Resources Specialists',
    wageLevel: 'III', offeredWage: 98000, prevailingWage: 92000,
    workLocation: 'San Francisco, CA 94105',
    filedDate: '2024-08-01', certifiedDate: '2024-08-12',
    validityStart: '2024-09-27', validityEnd: '2027-09-26',
    postingStartDate: '2024-08-12', postingEndDate: '2024-08-25',
    postingCompleted: true, pafComplete: true, status: 'certified',
  },
]

// ─── PAF Records ─────────────────────────────────────────────────────────────

export const pafRecords: PAFRecord[] = [
  {
    id: 'paf-001', lcaId: 'lca-001', employeeId: 'emp-001',
    completenessScore: 100,
    auditReady: true,
    lastUpdated: '2026-01-16',
    documents: [
      { name: 'Certified LCA (ETA-9035E)', required: true, present: true, fileId: 'doc-003' },
      { name: 'Prevailing Wage Documentation', required: true, present: true, fileId: 'doc-010' },
      { name: 'Actual Wage Documentation', required: true, present: true, fileId: null },
      { name: 'Posting Notice (10-day proof)', required: true, present: true, fileId: null },
      { name: 'Benefits Documentation', required: true, present: true, fileId: null },
      { name: 'Union Notice (if applicable)', required: false, present: false, fileId: null },
    ],
  },
  {
    id: 'paf-002', lcaId: 'lca-002', employeeId: 'emp-002',
    completenessScore: 60,
    auditReady: false,
    lastUpdated: '2026-02-10',
    documents: [
      { name: 'Certified LCA (ETA-9035E)', required: true, present: true, fileId: null },
      { name: 'Prevailing Wage Documentation', required: true, present: false, fileId: null },
      { name: 'Actual Wage Documentation', required: true, present: true, fileId: null },
      { name: 'Posting Notice (10-day proof)', required: true, present: true, fileId: null },
      { name: 'Benefits Documentation', required: true, present: false, fileId: null },
      { name: 'Union Notice (if applicable)', required: false, present: false, fileId: null },
    ],
  },
  {
    id: 'paf-003', lcaId: 'lca-003', employeeId: 'emp-008',
    completenessScore: 100,
    auditReady: true,
    lastUpdated: '2024-10-01',
    documents: [
      { name: 'Certified LCA (ETA-9035E)', required: true, present: true, fileId: 'doc-007' },
      { name: 'Prevailing Wage Documentation', required: true, present: true, fileId: null },
      { name: 'Actual Wage Documentation', required: true, present: true, fileId: null },
      { name: 'Posting Notice (10-day proof)', required: true, present: true, fileId: null },
      { name: 'Benefits Documentation', required: true, present: true, fileId: null },
    ],
  },
]

// ─── Policy Updates ───────────────────────────────────────────────────────────

export const policyUpdates: PolicyUpdate[] = [
  {
    id: 'pol-001',
    title: 'USCIS Increases H-1B Lottery Registration Fee to $215',
    source: 'USCIS',
    publishedDate: '2026-02-15',
    summary: 'USCIS has finalized a rule increasing the H-1B electronic registration fee from $10 to $215 per beneficiary, effective March 22, 2026.',
    fullText: 'The fee increase is intended to fund USCIS operations and reduce frivolous registrations...',
    affectedVisaTypes: ['H-1B'],
    impactLevel: 'medium',
    actionRequired: true,
    actionItems: ['Update budget for FY2027 H-1B cap season', 'Confirm Nadia Kovacs registration fee paid'],
    affectedEmployeeCount: 1,
    tags: ['fees', 'h1b', 'cap'],
  },
  {
    id: 'pol-002',
    title: 'DHS Announces Enhanced I-9 Enforcement Initiative',
    source: 'ICE',
    publishedDate: '2026-01-30',
    summary: 'ICE has announced a nationwide I-9 compliance initiative targeting the technology sector. Audit notices (Form I-9 Notice of Inspection) to be issued with 3 business days notice.',
    fullText: 'The initiative focuses on employers in the tech sector with over 10 foreign national employees...',
    affectedVisaTypes: ['H-1B', 'L-1A', 'L-1B', 'O-1A', 'OPT', 'STEM OPT'],
    impactLevel: 'high',
    actionRequired: true,
    actionItems: [
      'Complete I-9 self-audit immediately',
      'Correct Andrei Popescu I-9 errors ASAP',
      'Reverify Aisha Okonkwo I-9 when EAD received',
      'Ensure all PAFs are complete and accessible within 1 business day',
    ],
    affectedEmployeeCount: 6,
    tags: ['i9', 'enforcement', 'audit', 'urgent'],
  },
  {
    id: 'pol-003',
    title: 'Visa Bulletin March 2026: EB-2 India Advances 2 Months',
    source: 'DOS',
    publishedDate: '2026-02-10',
    summary: 'The March 2026 Visa Bulletin shows EB-2 India advancing to January 1, 2013. Employees with priority dates before Jan 2013 may be able to file I-485.',
    fullText: 'Final action dates for employment-based preferences...',
    affectedVisaTypes: ['Green Card'],
    impactLevel: 'medium',
    actionRequired: false,
    actionItems: ['Review priority dates for all employees with pending PERM/I-140'],
    affectedEmployeeCount: 1,
    tags: ['visa-bulletin', 'green-card', 'eb2'],
  },
  {
    id: 'pol-004',
    title: 'DOL Publishes Updated Prevailing Wages for FY2026 (OES)',
    source: 'DOL',
    publishedDate: '2026-01-05',
    summary: 'DOL has published updated OES wage data. Employers must ensure offered wages meet new prevailing wage levels for any LCA filings after January 5, 2026.',
    fullText: 'The FY2026 OES wage data shows significant increases in technology occupations...',
    affectedVisaTypes: ['H-1B', 'H-1B1', 'E-3'],
    impactLevel: 'high',
    actionRequired: true,
    actionItems: [
      'Verify offered wages for all open LCAs against FY2026 OES data',
      'Check Wei Zhang LCA wage level compliance',
      'Check Lucas Silva E-3 LCA wage compliance',
    ],
    affectedEmployeeCount: 3,
    tags: ['prevailing-wage', 'lca', 'dol'],
  },
  {
    id: 'pol-005',
    title: 'USCIS Processing Times Update: H-1B Up to 8 Months Without Premium',
    source: 'USCIS',
    publishedDate: '2026-03-01',
    summary: 'USCIS has updated processing times. H-1B regular processing now averaging 7-8 months at VSC and TSC. Premium processing (Form I-907) still 15 business days.',
    fullText: 'Updated processing times as of March 2026...',
    affectedVisaTypes: ['H-1B'],
    impactLevel: 'medium',
    actionRequired: false,
    actionItems: ['Consider premium processing for all upcoming H-1B filings'],
    affectedEmployeeCount: 4,
    tags: ['processing-times', 'h1b', 'premium-processing'],
  },
]

// ─── Alerts ──────────────────────────────────────────────────────────────────

export const alerts: Alert[] = [
  {
    id: 'alert-001', type: 'action_required', severity: 'critical',
    title: 'CRITICAL: Andrei Popescu — Unauthorized Work Risk',
    description: "H-1B expired 2/13/2025. MTR NOID response due 3/25/2026. Employee may not work until resolved. Consult immigration attorney immediately.",
    employeeId: 'emp-007', employeeName: 'Andrei Popescu',
    dueDate: '2026-03-25', createdAt: '2026-02-20', read: false,
    actionUrl: '/dashboard/employees/emp-007',
  },
  {
    id: 'alert-002', type: 'action_required', severity: 'critical',
    title: 'CRITICAL: Aisha Okonkwo — I-9 Reverification Overdue',
    description: 'OPT EAD expired 8/20/2024. STEM OPT EAD application pending. I-9 reverification cannot be completed until new EAD received.',
    employeeId: 'emp-004', employeeName: 'Aisha Okonkwo',
    dueDate: '2026-03-25', createdAt: '2024-08-21', read: false,
    actionUrl: '/dashboard/compliance/i9-audit',
  },
  {
    id: 'alert-003', type: 'expiration', severity: 'warning',
    title: 'Wei Zhang — Work Authorization Expiring in 50 Days',
    description: 'L-1B visa expires May 12, 2026. H-1B change of status petition filed and pending.',
    employeeId: 'emp-002', employeeName: 'Wei Zhang',
    dueDate: '2026-05-12', createdAt: '2026-03-22', read: false,
    actionUrl: '/dashboard/employees/emp-002',
  },
  {
    id: 'alert-004', type: 'deadline', severity: 'warning',
    title: 'PAF Incomplete: Wei Zhang LCA',
    description: 'Public Access File for LCA I-200-26001-234567 is 60% complete. Missing prevailing wage docs and benefits documentation.',
    employeeId: 'emp-002', employeeName: 'Wei Zhang',
    dueDate: null, createdAt: '2026-02-10', read: true,
    actionUrl: '/dashboard/documents/paf',
  },
  {
    id: 'alert-005', type: 'policy_change', severity: 'info',
    title: 'New Policy: DHS I-9 Enforcement Initiative',
    description: 'ICE announced tech sector audit initiative. Review I-9 compliance posture and address all open issues.',
    employeeId: null, employeeName: null,
    dueDate: null, createdAt: '2026-01-30', read: true,
    actionUrl: '/dashboard/policies',
  },
  {
    id: 'alert-006', type: 'expiration', severity: 'warning',
    title: 'Carlos Mendez — TN Expiring in 290 Days',
    description: 'TN status expires January 8, 2026. Begin renewal process 90 days before expiry.',
    employeeId: 'emp-003', employeeName: 'Carlos Mendez',
    dueDate: '2026-01-08', createdAt: '2026-01-23', read: true,
    actionUrl: '/dashboard/employees/emp-003',
  },
]

// ─── Compliance Deadlines ─────────────────────────────────────────────────────

export const complianceDeadlines: ComplianceDeadline[] = [
  {
    id: 'dl-001', employeeId: 'emp-007', employeeName: 'Andrei Popescu',
    type: 'MTR Response', description: 'AAO NOID response due — MTR for H-1B denial',
    dueDate: '2026-03-25', daysUntilDue: 2,
    priority: 'critical', status: 'in_progress', assignedTo: 'Ogletree Deakins',
  },
  {
    id: 'dl-002', employeeId: 'emp-004', employeeName: 'Aisha Okonkwo',
    type: 'I-9 Reverification', description: 'Complete Section 3 upon receipt of STEM OPT EAD',
    dueDate: '2026-04-20', daysUntilDue: 28,
    priority: 'high', status: 'pending', assignedTo: 'HR Admin',
  },
  {
    id: 'dl-003', employeeId: 'emp-002', employeeName: 'Wei Zhang',
    type: 'PAF Completion', description: 'Complete PAF for LCA I-200-26001-234567 before work begins',
    dueDate: '2026-03-30', daysUntilDue: 7,
    priority: 'high', status: 'in_progress', assignedTo: 'HR Admin',
  },
  {
    id: 'dl-004', employeeId: 'emp-009', employeeName: 'Lucas Silva',
    type: 'E-3 Renewal', description: 'Begin E-3 renewal — consular appointment scheduling',
    dueDate: '2026-06-14', daysUntilDue: 83,
    priority: 'medium', status: 'pending', assignedTo: null,
  },
  {
    id: 'dl-005', employeeId: 'emp-003', employeeName: 'Carlos Mendez',
    type: 'TN Renewal', description: 'TN renewal at Canadian border crossing',
    dueDate: '2025-12-08', daysUntilDue: -105,
    priority: 'high', status: 'completed', assignedTo: 'Carlos Mendez',
  },
  {
    id: 'dl-006', employeeId: 'emp-010', employeeName: 'Nadia Kovacs',
    type: 'H-1B Cap Registration', description: 'FY2027 H-1B lottery registration (if not selected)',
    dueDate: '2026-03-25', daysUntilDue: 2,
    priority: 'high', status: 'completed', assignedTo: 'HR Admin',
  },
  {
    id: 'dl-007', employeeId: 'emp-001', employeeName: 'Priya Sharma',
    type: 'I-9 Reverification', description: 'Reverify work authorization when H-1B I-94 nears expiry',
    dueDate: '2029-03-14', daysUntilDue: 1087,
    priority: 'low', status: 'pending', assignedTo: null,
  },
]

// ─── Org Compliance Score ─────────────────────────────────────────────────────

export const orgComplianceScore: OrgComplianceScore = {
  overall: 72,
  i9Score: 65,
  pafScore: 80,
  deadlineScore: 70,
  documentScore: 78,
  trend: 'down',
  trendValue: 5,
  lastUpdated: '2026-03-23',
}

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const dashboardStats = {
  totalEmployees: employees.length,
  activeEmployees: employees.filter(e => e.status === 'active').length,
  expiringSoon: employees.filter(e => e.status === 'expiring_soon').length,
  actionRequired: employees.filter(e => e.status === 'action_required' || e.status === 'expired').length,
  openCases: cases.filter(c => !['approved', 'certified', 'denied', 'withdrawn'].includes(c.status)).length,
  criticalAlerts: alerts.filter(a => a.severity === 'critical' && !a.read).length,
  pafCompliance: Math.round(pafRecords.filter(p => p.auditReady).length / pafRecords.length * 100),
  i9Errors: i9Records.filter(r => r.errors.length > 0).length,
}

// ─── Sample Chat History ──────────────────────────────────────────────────────

export const sampleChatMessages: ChatMessage[] = [
  {
    id: 'msg-001', role: 'assistant', timestamp: '2026-03-23T09:00:00Z',
    content: "Hello! I'm your ImmiCompliant AI Assistant, powered by specialized compliance agents. I can help you with:\n\n- **Compliance questions** with regulatory citations (8 CFR, INA, USCIS Policy Manual)\n- **Employee-specific analysis** — just ask about a specific person\n- **Document validation** and I-9 guidance\n- **Policy change impact assessments**\n\nWhat can I help you with today?",
    agentType: 'supervisor',
  },
  {
    id: 'msg-002', role: 'user', timestamp: '2026-03-23T09:01:00Z',
    content: "Can Andrei Popescu keep working while his MTR is pending?",
  },
  {
    id: 'msg-003', role: 'assistant', timestamp: '2026-03-23T09:01:08Z',
    content: `Based on Andrei Popescu's case file and the applicable regulations, **no — he generally cannot work while the MTR is pending under these circumstances.**

Here's the analysis:

**Situation**: Andrei's H-1B petition was denied, and a Motion to Reconsider (MTR) was filed with the AAO. The AAO has now issued a Notice of Intent to Deny (NOID).

**Key Rule — No Automatic Stay**: Filing an MTR does *not* automatically extend work authorization. The employee's H-1B status expired on February 13, 2025, and without an approved petition granting new or extended status, he lacks work authorization.

**Cap-Gap Does Not Apply**: Cap-gap protection (8 CFR § 214.2(h)(2)(i)(H)) only applies to F-1 OPT holders transitioning to H-1B cap-subject status — not to H-1B denials.

**Risk to the Employer**: Allowing unauthorized work exposes TechCorp to civil penalties of **$698–$27,894 per violation** under INA § 274A(e)(4).

**Recommended Immediate Actions**:
1. Place Andrei on unpaid leave immediately
2. Have counsel respond to the AAO NOID by **March 25, 2026** (2 days)
3. Simultaneously explore emergency O-1A filing or other alternatives
4. Do not allow return to work until a new approval notice (I-797) is received`,
    agentType: 'qa_agent',
    citations: [
      { source: '8 CFR § 214.2(h)(2)(i)(H)', text: 'Cap-gap extension provisions for F-1 to H-1B transitions' },
      { source: 'INA § 274A(e)(4)', text: 'Civil penalties for employing unauthorized workers' },
      { source: 'USCIS Policy Manual Vol. 2, Part B', text: 'H-1B nonimmigrant visa procedures' },
    ],
  },
]

// ─── Compliance Score History (for charts) ───────────────────────────────────

export const complianceScoreHistory = [
  { month: 'Oct', score: 88, i9: 85, paf: 92, deadlines: 90 },
  { month: 'Nov', score: 84, i9: 80, paf: 90, deadlines: 85 },
  { month: 'Dec', score: 80, i9: 75, paf: 88, deadlines: 82 },
  { month: 'Jan', score: 77, i9: 70, paf: 85, deadlines: 78 },
  { month: 'Feb', score: 74, i9: 67, paf: 82, deadlines: 74 },
  { month: 'Mar', score: 72, i9: 65, paf: 80, deadlines: 70 },
]

export const visaDistribution = [
  { name: 'H-1B', value: 3, color: '#3b82f6' },
  { name: 'L-1B', value: 1, color: '#8b5cf6' },
  { name: 'O-1A', value: 1, color: '#06b6d4' },
  { name: 'TN', value: 1, color: '#10b981' },
  { name: 'OPT/STEM', value: 2, color: '#f59e0b' },
  { name: 'Green Card', value: 1, color: '#6366f1' },
  { name: 'E-3', value: 1, color: '#ec4899' },
]
